language: java
dist: trusty

before_install:
  - 'wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh'

install: echo "I trust Maven."

# don't just run the tests, also run error-prone
script: mvn verify

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - os: linux
      env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10

notifications:
  email:
    recipients:
      - ryan@10e.us

