---
name: "Qodana"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - 'release/*'

jobs:
  qodana:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
      checks: "write"
      security-events: "write"
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@31d6f3309b31c566758e1314a3d9ef0dff75ecbd # v2024.2.6
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: github/codeql-action/upload-sarif@4dd16135b69a43b6c8efb853346f8437d92d3c93 # v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
